# --- Security headers (HSTS + hardening) ---
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# --- Functions config: spune lui Netlify unde sunt funcțiile ---
[functions]
  directory = "netlify/functions"

# --- Decap OAuth: permite sub-rutele /authorize și /callback pe același handler ---
[[redirects]]
  from = "/.netlify/functions/oauth/*"
  to   = "/.netlify/functions/oauth"
  status = 200
  force  = true
