# Netlify configuration for HTTPS & headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = '''max-age=63072000; includeSubDomains; preload'''
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 👉 spune lui Netlify unde sunt funcțiile
[functions]
  directory = "netlify/functions"

# 👉 permite sub-rutele /authorize și /callback pe același handler
# Redirect all subpaths of /oauth to the same function
[[redirects]]
  from = "/.netlify/functions/oauth/*"
  to = "/.netlify/functions/oauth"
  status = 200
  force = true
