# --- Global security headers (site) ---
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# --- Force HTTPS on www (evită mixed content) ---
[[redirects]]
  from = "http://www.zentryxdigital.co.uk/*"
  to   = "https://www.zentryxdigital.co.uk/:splat"
  status = 301
  force  = true

# --- Force HTTPS + canonical pe apex -> www ---
[[redirects]]
  from = "http://zentryxdigital.co.uk/*"
  to   = "https://www.zentryxdigital.co.uk/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://zentryxdigital.co.uk/*"
  to   = "https://www.zentryxdigital.co.uk/:splat"
  status = 301
  force  = true

# --- Functions location ---
[functions]
  directory = "netlify/functions"

# --- CMS-only CSP pe /admin (pagina goală) ---
[[headers]]
  for = "/admin"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://unpkg.com;
      script-src 'self' https://unpkg.com 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' blob:;
      script-src-elem 'self' https://unpkg.com 'unsafe-inline';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src https://fonts.gstatic.com data:;
      img-src * data: blob:;
      connect-src 'self' https://unpkg.com https://api.github.com https://github.com https://uploads.github.com https://www.zentryxdigital.co.uk;
      worker-src 'self' blob:;
      base-uri 'self';
      frame-ancestors 'self';
      form-action 'self';
    """

# --- CMS-only CSP pe /admin/* (app-ul Decap) ---
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self' https://unpkg.com;
      script-src 'self' https://unpkg.com 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval' blob:;
      script-src-elem 'self' https://unpkg.com 'unsafe-inline';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src https://fonts.gstatic.com data:;
      img-src * data: blob:;
      connect-src 'self' https://unpkg.com https://api.github.com https://github.com https://uploads.github.com https://www.zentryxdigital.co.uk;
      worker-src 'self' blob:;
      base-uri 'self';
      frame-ancestors 'self';
      form-action 'self';
    """
