# --- Global security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# --- Functions location ---
[functions]
  directory = "netlify/functions"

# --- Decap OAuth: route all subpaths to the same function handler ---
[[redirects]]
  from = "/.netlify/functions/oauth/*"
  to   = "/.netlify/functions/oauth"
  status = 200
  force  = true

# --- CMS-only CSP so /admin can load Decap safely ---
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src https://fonts.gstatic.com data:;
      img-src * data: blob:;
      connect-src 'self' https://api.github.com https://github.com https://unpkg.com;
      base-uri 'self';
      frame-ancestors 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """
