backend:
  name: github
  repo: autotechpartnersystem-oss/zentryx-landing
  branch: main
  # IMPORTANT: folosește URL absolut către funcțiile Netlify (evită probleme CORS/origin)
  base_url: "https://www.zentryxdigital.co.uk/.netlify/functions"
  # Endpointul de start pt OAuth; callback-ul devine automat /oauth/callback
  auth_endpoint: "oauth/authorize"

# Next.js servește doar din /public – mutăm media acolo
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "content/home.json"
        label: "Hero Section"
        name: "hero"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subhead (HTML allowed)", name: "subhead", widget: "text" }
          - { label: "Chips", name: "chips", widget: "list", field: { label: "Chip", name: "chip", widget: "string" } }
          - { label: "Primary CTA", name: "primary_cta", widget: "string" }
          - { label: "Secondary CTA", name: "secondary_cta", widget: "string" }
          - { label: "Header CTA", name: "header_cta", widget: "string" }
